id: Esz3mDjj
name: 八中调查表
template:
  - content: 尊重学生，公平、严格要求学生，师生关系和谐。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 具有良好的学科素养，知识面广，有深度。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 教学要求明确，重点突出，内容充实，课堂效率高。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 善于组织课堂教学，能调动学生积极参与，教学方法得当。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 善于进行学科学法指导，善于培养学生能力。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 能结合学科特点进行思想品德教育，关心学生全面发展，善于发现学生个性特长，并促进其发展。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 教态自然，大方得体。语言表达准确、清晰、流畅，富有感染力。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 教学示范作用好（如板书板画、多媒体运用、实验操作、诵读等）。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 作业量适中，有针对性，作业试卷批改认真，反馈及时，讲评效果好。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 能耐心细致地解答学生疑难，针对学生问题进行有效指导，并能根据需要进行心理辅导。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
  - content: 综合评价。
    kind: SINGLE_CHOICE
    options: 很满意|满意|一般|不满意
