development:
  adapter: mysql2
  encoding: utf8
  database: beikong-eshare-development
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true

test:
  adapter: mysql2
  encoding: utf8
  database: beikong-eshare-test
  username: root
  password: root
  pool: 5
  timeout: 5000
  
production:
  adapter: mysql2
  encoding: utf8
  database: beikong-eshare-production
  username: root
  password: root
  pool: 5
  timeout: 5000
  reconnect: true